DROP TABLE IF EXISTS "GOODS";

CREATE TABLE "GOODS"
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    price DOUBLE       NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS goods_id_seq START WITH 3 INCREMENT BY 1;

INSERT INTO "GOODS" (name, price)
VALUES ('Eggs', 100.0),
       ('Bread', 35.00);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    client  VARCHAR(100) NOT NULL,
    "DATE"  DATE         NOT NULL,
    address VARCHAR(100) DEFAULT NULL
);

CREATE SEQUENCE IF NOT EXISTS order_id_seq START WITH 3 INCREMENT BY 1;

INSERT INTO ORDERS (client, "DATE", address)
VALUES ('Dmitrii', '2021-11-08', 'Rostov-on-Don'),
       ('Ann', '2021-11-10', 'Moscow');

DROP TABLE IF EXISTS "ORDER_LINE";

CREATE TABLE "ORDER_LINE"
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    "ORDER_ID" INT NOT NULL,
    "GOODS_ID" INT NOT NULL,
    count      INT NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS order_line_id_seq START WITH 3 INCREMENT BY 1;

INSERT INTO "ORDER_LINE" ("ORDER_ID", "GOODS_ID", count)
VALUES (1, 1, 1),
       (2, 2, 2);