DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    client  VARCHAR(100) NOT NULL,
    "DATE"  DATE         NOT NULL,
    address VARCHAR(100) DEFAULT NULL
);

CREATE SEQUENCE IF NOT EXISTS order_id_seq START WITH 3 INCREMENT BY 1;

INSERT INTO ORDERS (client, "DATE", address)
VALUES ('Dmitrii', '2021-11-08', 'Rostov-on-Don'),
       ('Ann', '2021-11-10', 'Moscow');