DROP TABLE IF EXISTS "ORDER_LINE";

CREATE TABLE "ORDER_LINE"
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    "ORDER_ID" INT NOT NULL,
    "GOODS_ID" INT NOT NULL,
    count      INT NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS orderLine_id_seq START WITH 3 INCREMENT BY 1;

INSERT INTO "ORDER_LINE" ("ORDER_ID", "GOODS_ID", count)
VALUES (1, 1, 1),
       (2, 2, 2);